name: OpenSearch ODBC Driver

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'

env:
  CI_OUTPUT_PATH: "./ci-output"
  ODBC_LIB_PATH: "./build/odbc/lib"
  ODBC_BIN_PATH: "./build/odbc/bin"
  ODBC_BUILD_PATH: "./build/odbc/cmake"
  VCPKG_X64_INSTALL_PATH: ".\\src\\vcpkg_installed\\x64-windows"
  VCPKG_X86_INSTALL_PATH: ".\\src\\vcpkg_installed\\x86-windows"

# Tests are disabled (commented out) in all jobs because they are fail and/or outdated
# Keeping them for the brighten future when we can re-activate them
jobs:    
  build-mac:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Run cppcheck
      run: |
        brew install cppcheck
        sh run_cppcheck.sh
    - name: Upload cppcheck results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: cppcheck-results
        path: cppcheck-results.log
    - name: Get dependencies
      run: |
        brew install curl
        brew install cmake
        brew install libiodbc

    - name: Get vcpkg config fingerprint
      id: get-key
      run:  |
        echo key=`md5 src/vcpkg.json | cut -d ' ' -f 4`-mac >> $GITHUB_OUTPUT

    - name: Restore vcpkg cache
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: src/vcpkg_installed
        key: ${{ steps.get-key.outputs.key }}

    - name: Configure and build driver
      run: |
        ./build_mac_release64.sh

    - name: Save vcpkg cache
      uses: actions/cache/save@v3
      with:
        path: src/vcpkg_installed
        key: ${{ steps.get-key.outputs.key }}

    #- name: test
    #  run: | 
    #    bash ./run_test_runner.sh
    - name: Build installer
      if: success()
      run: |
        cd cmake-build64
        cmake ../src 
        make
        cpack .
        cd ..
    - name: Create-output
      if: success()
      run: |
        mkdir build-output
        mkdir test-output
        mkdir installer
        cp ./build/odbc/lib/*.dylib build-output/
        cp ./build/odbc/lib/*.a build-output/
        cp ./cmake-build64/*.pkg installer/
    # cp $(ls -d ./build/odbc/bin/* | grep -v "\.") build-output
    #    cp ./bin64/*.html test-output
    #    cp ./bin64/*.log test-output
    - name: Upload test
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: test
        path: |
          build
          cmake-build64
    #- name: Upload test results
    #  if: always()
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: mac-test-results
    #    path: test-output

 